name: syncrosong
description: A way to share songs across different music apps.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^1.2.0

  flutter_bloc: ^8.1.3

  webview_flutter: ^4.4.4
  url_launcher: ^6.2.4

  share_plus: ^7.2.2
  receive_sharing_intent: ^1.6.6

  fluttertoast: ^8.2.4

  go_router: ^13.2.1

  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  logging: ^1.2.0
  flutter_dotenv: ^5.1.0
  package_info_plus: ^5.0.1
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.8
  objectbox_generator: any

  #flutter_native_splash: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - local_properties.env

flutter_native_splash:
  color: "#FFFFFF"
  image: "lib/assets/splash_screen_logo.png"
  android_12:
    image: "lib/assets/splash_screen_logo_android_12.png"