// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/database/song_search/song_db_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1493004821366748285),
      name: 'SongDBModel',
      lastPropertyId: const obx_int.IdUid(5, 5083457390796461825),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8552008175875141140),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 411465260512973303),
            name: 'searchTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 335043929613188638),
            name: 'searchUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3907720544543287299),
            name: 'displayUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5083457390796461825),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 1493004821366748285),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [4508225432622317640],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        881479112126892328,
        8805207047466182260,
        4745228686876180532,
        7757961741493142523,
        5552733225234886090,
        1486731192973932040
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    SongDBModel: obx_int.EntityDefinition<SongDBModel>(
        model: _entities[0],
        toOneRelations: (SongDBModel object) => [],
        toManyRelations: (SongDBModel object) => {},
        getId: (SongDBModel object) => object.id,
        setId: (SongDBModel object, int id) {
          object.id = id;
        },
        objectToFB: (SongDBModel object, fb.Builder fbb) {
          final searchUrlOffset = object.searchUrl == null
              ? null
              : fbb.writeString(object.searchUrl!);
          final displayUrlOffset = object.displayUrl == null
              ? null
              : fbb.writeString(object.displayUrl!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.searchTime?.millisecondsSinceEpoch);
          fbb.addOffset(2, searchUrlOffset);
          fbb.addOffset(3, displayUrlOffset);
          fbb.addOffset(4, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final searchTimeValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final searchTimeParam = searchTimeValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(searchTimeValue);
          final searchUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final displayUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final object = SongDBModel(
              searchTimeParam, searchUrlParam, displayUrlParam, nameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SongDBModel] entity fields to define ObjectBox queries.
class SongDBModel_ {
  /// see [SongDBModel.id]
  static final id =
      obx.QueryIntegerProperty<SongDBModel>(_entities[0].properties[0]);

  /// see [SongDBModel.searchTime]
  static final searchTime =
      obx.QueryDateProperty<SongDBModel>(_entities[0].properties[1]);

  /// see [SongDBModel.searchUrl]
  static final searchUrl =
      obx.QueryStringProperty<SongDBModel>(_entities[0].properties[2]);

  /// see [SongDBModel.displayUrl]
  static final displayUrl =
      obx.QueryStringProperty<SongDBModel>(_entities[0].properties[3]);

  /// see [SongDBModel.name]
  static final name =
      obx.QueryStringProperty<SongDBModel>(_entities[0].properties[4]);
}
